name: grits
channels:
  - conda-forge
dependencies:
  - ele
  - freud
  - gsd
  - jupyterlab
  - mbuild
  - numpy
  - openbabel
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - python=3.8
  - rdkit
