name: build_cpu

on:
  push:
    branches: [ main ]
    # Run when container or environment is changed
    paths:
        - 'containers/dockerfile_cpu'
        - 'environment.yml'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  build_cpu:
    if: github.repository_owner == 'cmelab'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: grits
        tags: latest ${{ github.sha }}
        containerfiles: ./containers/dockerfile_cpu

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/repository/cmelab/grits
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
