name: pytest

on:
  push:
    branches:
      - main
    paths:
      - 'grits/**'
  pull_request:
    branches:
      - main
    paths:
      - 'grits/**'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
        image: cmelab/grits:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run pytest with coverage report
      run: python -m pytest -v -rs --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
